#!/usr/bin/env python3
"""Export a .tflite flatbuffer as the C array the firmware links against.

Replaces firmware/main/model_data.cc (the placeholder) with the real
model, preserving the alignas(16) attribute TFLite-Micro requires and the
g_model_data / g_model_data_len symbols declared in model_data.h.

Stdlib only. Usage:

    python export_c_array.py exports/pest_mnv2_int8.tflite
    python export_c_array.py model.tflite --out /path/to/model_data.cc
"""
import argparse
from pathlib import Path

HEADER = """\
/**
 * @file model_data.cc
 * @brief INT8 MobileNetV2 model — GENERATED by ml/export_c_array.py from
 *        {src} ({size} bytes). Do not edit by hand; retrain and re-export.
 */
#include "model_data.h"

alignas(16) const unsigned char g_model_data[] = {{
"""

FOOTER = """\
};
const size_t g_model_data_len = sizeof(g_model_data);
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("tflite", type=Path)
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parents[1]
                    / "firmware" / "main" / "model_data.cc")
    args = ap.parse_args()

    blob = args.tflite.read_bytes()
    if blob[4:8] != b"TFL3":
        raise SystemExit(f"error: {args.tflite} is not a TFLite flatbuffer "
                         "(missing TFL3 magic)")

    lines = []
    for i in range(0, len(blob), 12):
        chunk = blob[i:i + 12]
        lines.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
    body = "\n".join(lines) + "\n"

    args.out.write_text(
        HEADER.format(src=args.tflite.name, size=len(blob)) + body + FOOTER)
    print(f"{args.out} written — {len(blob)} bytes "
          f"({len(blob)/1024:.0f} KB). Rebuild with idf.py build.")


if __name__ == "__main__":
    main()
